### ISSUE TITLE
App Freezes when you switch shards

### ISSUE THREAD

**Issue by AsyncJakub** [aiko-chan-ai/DiscordBotClient#170]
It's not the biggest issue but it can be annoying. I have to force reload the app all the time.

**Comment by aiko-chan-ai** [comment]
How many servers does your bot have? I am currently unable to reproduce this issue.

**Comment by AsyncJakub** [comment]
111 Servers

**Comment by aiko-chan-ai** [comment]
With 111 servers, shard switching is not necessary, but there might be a bug that causes that command to work. (Bc 200 guilds per shard)

**Comment by AsyncJakub** [comment]
If I don't then I can't view all servers. I have 1 shard. 0-1 and when I switch between them then it just freezes. Sometimes it works but sometimes it doesn't

**Comment by aiko-chan-ai** [comment]
Perhaps I need a bot token to test that error.

**Comment by AsyncJakub** [comment]
I could try looking in dev console to see if there are any errors.

**Comment by AsyncJakub** [comment]
I just tried opening the app only to receive this error

![image](https://github.com/user-attachments/assets/05d7ccda-03c0-4b77-81c7-dbd13ed68087)

**Comment by aiko-chan-ai** [comment]
I’m back after a while.
I have a bot with over 600 servers, and I can't reproduce this error. 
However, it seems that the official web client also freezes when inactive, so I currently don’t have a workaround.

**Comment by Anyapappi** [comment]
how to switch between shards.

**Comment by VanillaChan6571** [comment]
I am able reproduce this. The 3 bots are in 3-5 server's each. When switching accounts. The App freezes on discord's "did you know"

**Comment by VanillaChan6571** [comment]
![image](https://github.com/user-attachments/assets/e494b054-b1cd-4e57-ac79-c6f278187746)

Or even just Control + F5 crashes the Bot Client..

**Comment by aiko-chan-ai** [comment]
It's really strange... I completely can't reproduce this error (I tried with a list of 5 bots, with the number of servers being approximately 300, 70, 5, 3, and 2, respectively).

**Comment by VanillaChan6571** [comment]
> It's really strange... I completely can't reproduce this error (I tried with a list of 5 bots, with the number of servers being approximately 300, 70, 5, 3, and 2, respectively).

Maybe its because I updated from 3.4.1 -> 3.5.0 and maybe there is a bad file?

**Comment by aiko-chan-ai** [comment]
Idk

**Comment by AsyncJakub** [comment]
> I am able reproduce this. The 3 bots are in 3-5 server's each. When switching accounts. The App freezes on discord's "did you know"

Yes it's literally exact that. It just randomly happens and I have to force restart it. (Not even that works sometimes)

**Comment by Apraxed** [comment]
having the same issue

**Comment by Natolix** [comment]
I can personally reproduce the same issue with a 2 servers bot. Strange thing, lol.

**Comment by AsyncJakub** [comment]
I honestly don't know how you recreated it. I feel like it happens 99% of the time.

**Comment by aiko-chan-ai** [comment]
I really can't reproduce it, but if you still feel there's an issue, do it like this.

![image](https://github.com/user-attachments/assets/7922a00b-131f-4ea3-8161-931349614a02)

**Comment by Kugyan** [comment]
How to get to that menu?

**Comment by AsyncJakub** [comment]
> How to get to that menu?

![image](https://github.com/user-attachments/assets/34c25e9d-ce67-4fde-a36e-60d2f57a2a8a)

Find the icon and then right click

**Comment by ferrenza** [comment]
Hey there same issue here!

but I have tried several methods.
We do not need to clear web storage / clear local database.

When the application logs in and the guild starts to load gradually on the current shard, use 1 guild that has send message access as a reference to perform `/switchguild` or `/switchshard` quickly.
The point is, our hands must be "fast hands," because if all the guilds in "1 shard" fully load, it will cause a hang, freeze, or get stuck.
For example, if you have 400 servers and several shards are available,
when the application starts, prevent the application from fully loading the server list in one shard.

**Comment by ferrenza** [comment]
> I’m back after a while. I have a bot with over 600 servers, and I can't reproduce this error. However, it seems that the official web client also freezes when inactive, so I currently don’t have a workaround.

Yes, this is correct. If we are not interacting with the app, or if it is idle for too long, it will cause the display to freeze.

However, if we are interacting with the app, such as scrolling, selecting a profile, etc., it does not cause a freeze.

**Comment by aiko-chan-ai** [comment]
Perhaps I’ll try limiting it to 100 guilds per shard?  
Although it's currently set to 200 guilds per shard (equivalent to Discord Nitro users), it’s strange to encounter such issues.

**Comment by ferrenza** [comment]
> Perhaps I’ll try limiting it to 100 guilds per shard? Although it's currently set to 200 guilds per shard (equivalent to Discord Nitro users), it’s strange to encounter such issues.

Yeah, you might want to try comparing with a limit of 100 or 50. If it still freezes, I have no idea what else could serve as a reference for this freeze issue 😂

The main point is, as the guilds load gradually, don’t let them all load at once. If we’re late, we need to force a reload and use the method I mentioned earlier.

**Comment by aiko-chan-ai** [comment]
fixed

**Comment by ferrenza** [comment]
> fixed

Nice work

btw there are a few things that are not fixed yet, including: when we switch to another application and stay idle for a while, then return to the application window, it experiences a slight freeze (it could be quick or slow). What do you think?

**Comment by aiko-chan-ai** [comment]
I think this is an issue with Discord. I've experienced it (and so have many others).  
https://www.reddit.com/r/discordapp/comments/1e3hfwq/discord_freezing_in_the_background/

This might be a potential fix:  
https://www.reddit.com/r/discordapp/comments/1dljeun/i_have_figured_out_a_temporary_fix_to_the_discord/

**Comment by ferrenza** [comment]
> I think this is an issue with Discord. I've experienced it (and so have many others). https://www.reddit.com/r/discordapp/comments/1e3hfwq/discord_freezing_in_the_background/
> 
> This might be a potential fix: https://www.reddit.com/r/discordapp/comments/1dljeun/i_have_figured_out_a_temporary_fix_to_the_discord/

alr

**Comment by ferrenza** [comment]
btw the apps keep pop up Update Manager say you are in newest version
opening & relaunch app

last question: how to show current bio? its always say "Based on the cutest Discord client mod :3"

**Comment by aiko-chan-ai** [comment]
> btw the apps keep pop up Update Manager say you are in newest version opening & relaunch app

I might make it stop appearing in the next version (v3.6.1)

> last question: how to show current bio? its always say "Based on the cutest Discord client mod :3"

When Discord allows you to do that

**Comment by ferrenza** [comment]
Hey, sorry for chatting in this thread again: Hey, I found a new issue here, an error message appears.

I opened the app -> my PC went into sleep mode because im idling -> after waking up, this message appeared.
![image](https://github.com/user-attachments/assets/ef83d7ba-dcf1-43dd-b125-7138e13581a6)

**Comment by aiko-chan-ai** [comment]
> Hey, sorry for chatting in this thread again: Hey, I found a new issue here, an error message appears.
> 
> I opened the app -> my PC went into sleep mode because im idling -> after waking up, this message appeared. ![image](https://private-user-images.githubusercontent.com/62527916/400136328-ef83d7ba-dcf1-43dd-b125-7138e13581a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5OTE1NTMsIm5iZiI6MTczNTk5MTI1MywicGF0aCI6Ii82MjUyNzkxNi80MDAxMzYzMjgtZWY4M2Q3YmEtZGNmMS00M2RkLWIxMjUtNzEzOGUxMzU4MWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDExNDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMTFhMDU5Yzk5MmY5NjY1MzQ4ZjQwYmM3NTc4Y2E1NzFjOWRmMzgzMjQ5MjM1ZGU1MjE1MzNjMDcwYmZhNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZEO2DVT3gViR5MkX9_GvRDeiN-AEwQFhA3r7IlmBFcM)


This occurs when the application sends a request to Discord just as your computer has recovered from sleep mode (without an immediate internet connection), leading to a connection error.  

To clarify, in previous versions, I used two events: `unhandledRejection` and `uncaughtException`, and this network connection error clearly did not appear (but it also caused inconvenience because I couldn't detect many other potential errors).  
In this version, the error is displayed using Electron's `MessageBox`, but it seems to block the render thread.  

You can normally close this notification.
